### PR TITLE
fix: use androidx

### PR DESCRIPTION
**Pull request by anees17861**
A change was made to use android support. All modern projects should be migrated to androidx

### CODE REVIEW

**Comment by fabiendem** [comment]
Damn I was looking at the exact same issue at the same time.
Thanks for the fix!!
Hopefully it can be merged soon 🤞

**Review by fabiendem — APPROVED** [review]

**Comment by fabiendem** [comment]
Hi @manualexSP, any chance we can merge this PR please?

**Comment by manualexSP** [comment]
@fabiendem & @anees17861 Hey guys thank you for doing this. I will talk with my team and we will do some tests with this change to see how it works on our end and we will come back to you with an update :D

**Comment by fabiendem** [comment]
It should fix the following warnings while running `jetify`.
```
Jetifier found 2181 file(s) to forward-jetify. Using 10 workers...
Jetifier: propose an AndroidX conversion PR to this repository: node_modules/react-native-nordic-dfu/android/src/main/java/com/pilloxa/dfu/NotificationActivity.java
Jetifier: propose an AndroidX conversion PR to this repository: node_modules/react-native-nordic-dfu/android/src/main/java/com/pilloxa/dfu/RNNordicDfuModule.java
```

**Pull request merged**
