### PR TITLE
RNNDFU: Update Nordic Android & iOS dependencies

### PR DESCRIPTION
**Pull request by manualexSP**
- Upgrade android.tools.build:gradle from 4.0.1 -> 7.2.1
- Upgrade no.nordicsemi.android:dfu from 2.0.1 -> 2.3.0
- Upgrade iOSDFULibrary from 4.11.1 -> 4.12.0

### CODE REVIEW

**Comment by manualexSP** [comment]
@anees17861 & @fabiendem Hey guys, since I saw that you were active on this fork I want to let you know that we are testing some new updates in the next couple of weeks we will release those changes.
So if you have some time to test these changes on your project to be sure that we won't spoil anything on your side, that would be great.

**Comment by fabiendem** [comment]
Thanks for the heads up @manualexSP !
I will share this with my colleagues.

**Comment by anees17861** [comment]
Thanks for notifying @manualexSP 
Will try to test it out as soon as possible.
Any app side changes that I should be doing?

**Comment by anees17861** [comment]
PS @manualexSP
Thank you for continuously maintaining this library. Saved me a ton of time trying to figure out the bridging

**Comment by manualexSP** [comment]
@fabiendem I don't think so. 
We had a crash on the app when we were doing a dfu update if we were targeting SDK 31+ (for android 12/13)
And starting this year google has not been allowing releases without targeting SDK 31+ so we did those changes and from what we tested on our side, everything looks good.

**Review by LucasHimelfarb — APPROVED** [review]

**Comment by LucasHimelfarb** [comment]
@manualexSP thanks a lot for your contribution!!!

**Comment by manualexSP** [comment]
Probably we will merge this PR on Monday

**Pull request merged**
